### ISSUE TITLE
Consider making transports into individual SvcParamKeys

### ISSUE THREAD

**Issue by ericorth** [MikeBishop/dns-alt-svc#112]
Instead of an "alpn" or "transports" list, perhaps each transport should be its own SvcParamKey.  Then the transport is considered supported for a record if the parameter appears in the SvcFieldValue parameter list for the record.  Maybe h1/TLS is still considered supported by default unless there's a parameter saying to not use defaults.

Advantages:
- Negates the recent debates over a wire format for the transport list.  Transports are now listed in the main SvcFieldValue parameters list using the wire format established for that list.  No need to decide between delimiter separation or length prefixing for a special sub-list.  No need to create a separate string list or value registry for the transport values, as it will just be entries from the SvcParamKey registry.  The parameters will be just as easy to deal with as any other parameters for people dealing with presentation format or text config files.
- Solves recent debates over potential per-transport sub parameters such as port.  Instead of a single "port" parameter or encoding port in transport name, transports can allocate bytes to port in the SvcFieldValue value.  This would likely be the only thing in the value for transports defined by the initial RFC, maybe with a value of 0 meaning to use the port from the qname.  Any transports added in the future could define whatever sub parameters make sense for that new transport type (or remove port entirely if non-default ports are disallowed for the new transport).
- Extensibility is consistent with the primary extensibility mechanism for SVCB, that is that adding new transports or changing sub parameters format means adding to the SvcParamKey registry.  New registry additions would have all the extensible flexibility as anything else added that way.

**Comment by bemasc** [comment]
That's an interesting proposal, and I agree with the advantages you've identified.  However, it does also have some disadvantages.
* Each new protocol is allocated from a finite numeric space, so draft protocol versions during development probably can't be expressed in this form.  (We do have a private range reserved in the registry, which might suffice, but conflicts in the private space could also lead to bad outcomes, especially if parsers reject the whole RRSet when there's a conflict.)
* Adding a new transport would require updating all the DNS-related components (authoritative and stub).  With "transport=..." new transports are opaque to the DNS-related components, so no updates are required.  (This can be hacked around using the `key1234` mechanism on the authoritative and possibly some escape hatch in SVCB client libraries, but it's ugly as heck.)
* Sharing a namespace with all the other keys could be confusing.
* If we want to add more sub-parameters to a transport later (e.g. QUIC versions), we likely can't, because its SvcParamValue format will already be fixed.

To match the current draft's behavior, we would need to define "quic", "tls", and "no-tls" keys.  However, I'm not sure that these keys actually make sense outside the context of a specific scheme (like HTTPS).  For example, can we really use the same "tls" key for all the different application-protocols that might be delivered over TLS?

> maybe with a value of 0 meaning to use the port from the qname

I would signal that using an empty SvcParamValue, and make "0" mean "disabled".  This would allow us to replace "no-tls" with "tls=0".

Overall, I'm neutral on this change.  I'd be more inclined to support it if we decided to make the SvcFieldValue a string-keyed map (CBOR!), but that's a much bigger change.

**Comment by ericorth** [comment]
Regarding difficulty adding new transports or changing sub-parameters, I would say that adding a new key (or a replacement key in the case of changing the value format to add new sub parameters) to the registry and updating things to handle it is the appropriate bar of difficulty.  We don't expect to need completely new protocols very often, and the extensibility is appropriate for the rare occasions when it will happen.  Yes, it leads to private space conflict issues for experimental new transports/versions, which is not ideal, but I would argue that anything with unregistered values is going to have pains to work around (eg unregistered names means adding a new one, development or final, still has to ensure you have a unique name without conflict).

**Comment by ericorth** [comment]
After thinking this through a bit more, I think if we have any concerns over transport extensibility using SvcParamKeys, since this is SVCB's main extensibility mechanism and transports don't seem to be something that will need to change more frequently than anything else, that this points to a more general issue with extensibility of SvcParamKeys.  Opened issue #113 to discuss that point.

**Comment by enygren** [comment]
Some of this is a matter of getting DNS zone management software updated, as well as updating any software that needs to translate from presentation to/from wire form.  Having some bar there is unavoidable with any binary format (although CBOR continues to be vaguely attractive and was my first proposal, but is a big change).  But keeping transport as a list of strings seems cleaner.

I continue to think we may wish to make transport a tightly constrained token (eg, /^[0-9a-z-]{1,8}$/ or similar) to avoid the mess ALPN creates.

**Comment by bemasc** [comment]
This issue is obsolete, since we have switched to conveying ALPN (and specified that it is essentially advisory, with clients and servers still performing full ALPN negotiation via TLS).
