### ISSUE TITLE
Clarify how ALPN interacts with ECHO

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#132]
With Encrypted Client Hello there is an ALPN on both the outer (exposed) and the inner (encrypted).  We should clarify how this interacts with the alpn= attribute.

**Comment by enygren** [comment]
See related on ESNI/ECHO:  https://github.com/tlswg/draft-ietf-tls-esni/issues/216

**Comment by MikeBishop** [comment]
There are a couple of concepts implicated here:

- What does the server advertise that it speaks?  That's the content of the SVCB record.  Note that this cannot be private information, since anyone could retrieve the DNS record.
- What does the client want to admit that it speaks / is planning to speak?  That's the content of the public ClientHello.
- What does the client actually want to speak?  That's the content of the encrypted ClientHello.

In most situations I can think of, it's the client that wants to conceal that it's using a particular protocol (e.g. a VPN tunnel), and so client policy would dictate when the public/private ALPN tokens differ.  Put something innocuous in the public ALPN extension, or even omit it.

If the server wants to conceal that it speaks a particular protocol, DNS is not the place to publish that information.  There might be value in a mechanism for the server to advertise "secret" ALPN tokens that it supports for the client's future use in encrypted ClientHellos, but I don't think SVCB is the venue for that.  It would need to be something it can provide only to already-authenticated clients -- perhaps something it could attack to an NST?

**Comment by sftcd** [comment]
Hiya,

On 14/04/2020 15:37, Mike Bishop wrote:
> There are a couple of concepts implicated here:
> 
> - What does the server advertise that it speaks?  That's the content of the SVCB record.  Note that this cannot be private information, since anyone could retrieve the DNS record.
> - What does the client want to admit that it speaks / is planning to speak?  That's the content of the public ClientHello.
> - What does the client actually want to speak?  That's the content of the encrypted ClientHello.
> 

There's also an additional part - a server might be telling
clients how to better not stick out or how to get interop
if some other common choice might cause failures. I doubt
we can know for sure how to treat those for now.

> In most situations I can think of, it's the client that wants to conceal that it's using a particular protocol (e.g. a VPN tunnel), and so client policy would dictate when the public/private ALPN tokens differ.  Put something innocuous in the public ALPN extension, or even omit it.
> 

I doubt many clients will have such a rich policy. I'd
expect that client implementers will just pick something.

I think the minimum we need to do is to say that
HTTPSSVC.alpn is to be used in inner CH if ECHO is being
used. It might also make sense to define a public_alpn
field either in ECHOConfig or HTTPSSVC and to then say
that if only one of those is present, then the same
value SHOULD be used in inner and outer and if both are
present, then clients SHOULD follow what the server
said. (And if we do do that, I'd argue to have the
public_alpn in the same structure as the public_name,
whether that's ECHOConfig or HTTPSSVC.)

> If the server wants to conceal that it speaks a particular protocol, DNS is not the place to publish that information.

Well... that same logic would call ESNI/ECHO into question
entirely wouldn't it? So I don't find the argument below
convincing.

S

>  There might be value in a mechanism for the server to advertise "secret" ALPN tokens that it supports for the client's future use in encrypted ClientHellos, but I don't think SVCB is the venue for that.  It would need to be something it can provide only to already-authenticated clients -- perhaps something it could attack to an NST?
>

**Comment by MikeBishop** [comment]
> > If the server wants to conceal that it speaks a particular protocol, DNS is not the place to publish that information.
> Well... that same logic would call ESNI/ECHO into question entirely wouldn't it? So I don't find the argument below convincing.

No, it wouldn't; the ESNI/ECHO keys are inherently public information.  They can (and should) be widely disseminated.  The fact that a server supports ECHO is similarly not private.  If you're assuming that the server's set of supported protocols *is* private information, then you need a private way to distribute that information.  ECHO, of course, only permits the transfer of private information from client to server.

That said, I don't object to ECHOConfig suggesting innocuous settings for other properties for use on the public side if the TLS WG wants to do that.  (@davidben makes a good point that the public name is less for innocuous value and more for delegating the authority to change config, though.)  I think that's orthogonal to SVCB telling you what the service supports and how to access it.

**Comment by davidben** [comment]
I don't think discussion about which ALPN to use in TLS makes sense HTTPSSVC, except in so far as clarifying that the thing HTTPSSVC calls ALPN gets little to no on influence the TLS ALPN decision. (I.e. we must revert the Alt-Svc original sin.)

Beyond that, for ECHO's semantics, the answer is clear: the inner ClientHello is the actual ClientHello. The client should put in the ALPN parameters it actually wants to negotiate. The outer ClientHello is to authenticate a key mismatch signal, so negotiated parameters only matter up to authenticating that signal. Thus, ECHO has opinions on the outer name because it selects the authenticating certificate. The outer ALPN doesn't seem very important.

Either way, whether you got your ECHO config from HTTPSSVC or some hypothetical other channel, those same considerations hold, so any decisions here belong in ECHO, not HTTPSSVC.

**Comment by bemasc** [comment]
Since it's been mentioned a few times, I want to clarify that the SVCB "alpn=" field does _not_ tell the client what to put in its ALPN field, at least not directly.  It tells the client about what ALPNs the _server_ supports, so that the client can choose transports that will work.  As the text (currently) notes

> Clients SHOULD also include any other values that they support and could negotiate on that connection with equivalent or better security properties. For example, if the ALPN set only contains "http/1.1", the client could include "http/1.1" and "h2" in the ProtocolNameList.

I agree that this text is talking about the inner ClientHello, and we need to make that clear in the drafts.

**Comment by enygren** [comment]
Is what we have there now good enough?
(Or do we also want to mention ALPN on the outer?
The echo draft has:

> It then constructs a new ClientHello (ClientHelloOuter) with an innocuous SNI
>    (and potentially innocuous versions of other extensions such as ALPN
>    [RFC7301]) and containing the encrypted ClientHelloInner as an
>    extension.

**Comment by MikeBishop** [comment]
Addressed as part of #148.
