### ISSUE TITLE
Larger SvcParamKey space for experiments and first-come-first-served allocations

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#154]
Having only 256 experimental SvcParamKeys may not be enough.
Proposed would be to leave the first 32k as expert review,
most of the next 32k as first-come-first-served, and some
subset (256) as experimental/private-use.

**Comment by enygren** [comment]
See also #113

**Comment by chris-wood** [comment]
This seems like a pretty reasonable plan to me. Without a change like this, doing experiments seems like it'd be challenging.

**Comment by tfpauly** [comment]
Since I requested this change, I'm clearly in favor of it too =)

Should we bring this up with WG as a discussion item?

**Comment by bemasc** [comment]
I don't see this as terribly contentious.  I would just do it, and highlight it for discussion in the changelog we send to the WG.

Also, I'm tempted to make codes 1-255 "RFC Required".

**Comment by tfpauly** [comment]
That all sounds good to me

**Comment by ericorth** [comment]
I still prefer #113, but I recognize that I'm clearly biased (because I opened #113 and because I only deal with client-side where the additional bytes are mostly free).  This proposal seems to be a reasonable compromise that greatly mitigates the main issue of 256 keys being completely insufficient for experimentation.  So overall, SGTM!

Re WG discussion: I wouldn't expect this to be contentious enough to require discussion before adding to the next draft.

Re a small RFC-Required block: Assuming the primary motivation would be to save the "good" low numbers for the really important things (rather than concerns over running out of points), I would argue that we should make it even stricter ("Standards Action") since I see no reason Informational or Experimental drafts to get the distinction.
