### ISSUE TITLE
Mandating DoS

### ISSUE THREAD

**Issue by martinthomson** [MikeBishop/dns-alt-svc#191]
The text in Section 3.1 correctly identifies a number of ways in which a client might be denied access to a SVCB record.  I don't know if this is exhaustive, but it seems like a reasonable start.  It then mandates (using "MUST NOT") very specific behaviour.  That mandated behaviour ends up making the service effectively unreachable.

It is not appropriate for this document to set policy for clients in this way.  It is clear that this is biased toward ensuring that secured alternative methods for reaching a service are known to a client, but I don't think that this is the only way to achieve that goal.  All this does is make the system more likely to be brittle and prone to denial of service.

**Comment by bemasc** [comment]
This is a "MUST NOT" because otherwise ECH is vulnerable to a downgrade attack: if a MITM between Firefox and the DoH server drops just the packets containing SVCB responses (likely identifiable by size or timing), they will eventually time out.  If the client falls back to ordinary connection, they'll lose the ECH protection.  (QUIC makes this attack especially easy.)

If ECH doesn't need to be downgrade-resistant in this way, then we can relax the requirement, but the ECH experts I've talked to seem to think that this threat type is in-scope.

**Comment by martinthomson** [comment]
Why make the requirement generic though?  There is already text in Section 8.1 that addresses the problem of ECH downgrade (though it is not complete, see #196).

**Comment by bemasc** [comment]
I remembered another reason: the downgrade protection also applies to the HTTPS upgrade functionality, so fallback-on-error would allow the MITM to disable HTTPS upgrade.

An alternative to the current spec would be: "on error, the HTTPS upgrade still applies as if the record were present, and if the client supports ECH, it must abandon the connection entirely".  That seems like more spec complexity for very limited gain (assuming most clients do implement ECH), but I think it would be safe.

**Comment by martinthomson** [comment]
We should not place any weight on this mechanism when it comes to downgrades.

I'm not suggesting that ECH advice needs to change (except as described in #196, perhaps), but instead suggesting that the generic advice not be so strong.

**Comment by enygren** [comment]
Proposal from discussion: change to SHOULD and then have text in security considerations saying why you REALLY OUGHT TO
