### ISSUE TITLE
Period is owner name for additional section processing is different to every other type.

### ISSUE THREAD

**Issue by marka63** [MikeBishop/dns-alt-svc#203]
For every other type the next name to be looked up is embedded in the rdata itself.  Additional "." often means "no such service".   For BIND adding "." is owner name meant touching 102 files as every other RR types method for processing additional data needed to changed as well as every place where additional data is added to the response.

I'm wondering if making "." special like this is worth it? 

I'm also wondering if we should be giving up the ability to signal "no such service" as is done in SRV, MX is worth it?

**Comment by bemasc** [comment]
> For BIND adding "." is owner name meant touching 102 files as every other RR types method for processing additional data needed to changed

That's definitely surprising!  We didn't think this would be complicated to implement.

> I'm wondering if making "." special like this is worth it?

The most important thing to me is that we have a way to encourage SvcDomainName == owner name when editing the zone file, because this reduces latency under certain conditions.  Perhaps we could use `*` or `-` instead of `.` in the zone file.

Repeating the owner name, without the benefit of name compression, is a bit annoying.  Can you think of a way to avoid the duplication that would be easier for BIND?  It's too bad we don't have a name-compression mode that works within an RR.

> I'm also wondering if we should be giving up the ability to signal "no such service" as is done in SRV, MX is worth it?

I haven't heard anyone ask for this, so I don't consider it a priority.  If there's an easy way to signal it I'd be OK with including it, but we'd have to think carefully about what it means.  (If there's no HTTPS service, does that mean there's no HTTP service either?)

**Comment by tfpauly** [comment]
Keeping the wire format small and simple for having the name match is important, so I think that part should stay as is. I don’t have much preference for the presentation format here. “.” makes sense by matching the normal interpretation of a zero-length label. However, some other presentation format symbol does as well here. 

For BIND, it’d be nice to hear more clarity for why this was complex. Can the parsing not easily be specialized per type?

As for communicating that there is no such service, I’d be concerned to see that for things like HTTPS. These are hints that should help upgrade connections to more secure mechanisms (ECH, HTTP/3, etc), but being able to say “don’t do https” or similar sounds problematic. Unless there’s a use case, I’d argue to leave such functionality off for now.

**Comment by enygren** [comment]
Would using something else with the same meaning help?  For example, "=" or "~" or "^" or something might avoid confusion with other uses of "."  (which would then just be a single label containing that character in the wire format).

**Comment by marka63** [comment]
> > For BIND adding "." is owner name meant touching 102 files as every other RR types method for processing additional data needed to changed
> 
> That's definitely surprising! We didn't think this would be complicated to implement.

You changed the additional section processing paradigm.  Most of those 102 files was saying "the owner name is not used in this method".  Part of it was actually passing the name from higher up in the calling stack.  When a nameserver looks up the addresses associates with a NS record it doesn't care about the owner name of the NS record.  It just looks at the RDATA of the record.  The same applies for every other record except these two proposed ones.

https://gitlab.isc.org/isc-projects/bind9/-/merge_requests/2135/diffs?commit_id=232cb0d53bd3ba4f9b3fb0d80d903916b917627c

> > I'm wondering if making "." special like this is worth it?
> 
> The most important thing to me is that we have a way to encourage SvcDomainName == owner name when editing the zone file, because this reduces latency under certain conditions. Perhaps we could use `*` or `-` instead of `.` in the zone file.

You are assuming that it will take a lot of time for recursive servers to learn about these records.   That is not reality.
Some nameservers do speculative lookups of records missed (no RRset, no cached no data, no cached nxdomain) when doing additional section processing.  BIND does one lookup but it could be made to do more.

> Repeating the owner name, without the benefit of name compression, is a bit annoying. Can you think of a way to avoid the duplication that would be easier for BIND? It's too bad we don't have a name-compression mode that works within an RR.

Well if you really want it you would need to signal that the client supports intra RR compress for these types.  That is easy enough to do with a EDNS option (option code + list of types the client supports intra RR compression for).  You would need to get a label type assigned for intra RR compression pointers.   IANA already maintains a registry.  The server would need to do case sensitive compression to preserve DNSSEC signatures for when the record was returned to canonical form for DNSSEC processing.

https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-10

> > I'm also wondering if we should be giving up the ability to signal "no such service" as is done in SRV, MX is worth it?
> 
>  I haven't heard anyone ask for this, so I don't consider it a priority. If there's an easy way to signal it I'd be OK with including it, but we'd have to think carefully about what it means. (If there's no HTTPS service, does that mean there's no HTTP service either? What if there are multiple RRs, and only one has this flag?)

**Comment by bemasc** [comment]
> Most of those 102 files was saying "the owner name is not used in this method".

Thanks for clarifying.  I presume you're referring to [this change](https://gitlab.isc.org/isc-projects/bind9/-/commit/232cb0d53bd3ba4f9b3fb0d80d903916b917627c) in your experimental branch.

I'm not familiar with the BIND code, but this seems like a reasonable implementation to me, and suggests that the current spec is not too bad.

> You are assuming that it will take a lot of time for recursive servers to learn about these records.

Mostly I'm just counting roundtrips.  SVCB queries are always issued in parallel to A/AAAA queries, so if SvcDomainName == owner-name, then there are already queries in flight for the necessary addresses (0 extra roundtrips).  Anything that requires a followup query, whether by the recursive or by the client, adds some amount of latency.

> Well if you really want it you would need to signal that the client supports intra RR compress for these types. That is easy enough to do with a EDNS option ...

If something like this already existed I think we would use it here, but inventing and standardizing it seems like a big project, not justified by the size of the problem.

I was thinking of something to avoid special-casing "." in this way, e.g. "The SvcDomainName is represented with a one-octet length prefix, followed by a buffer of that length.  The buffer contains a domain name that fills the buffer.  If the name is fully-qualified (ending in an empty label) then it is an absolute name; otherwise it is relative to the owner name.".  However, I expect this would make your implementation more complex, not less, so I'm not suggesting this change.

**Comment by marka63** [comment]
> > Most of those 102 files was saying "the owner name is not used in this method".
> 
> Thanks for clarifying. I presume you're referring to [this change](https://gitlab.isc.org/isc-projects/bind9/-/commit/232cb0d53bd3ba4f9b3fb0d80d903916b917627c) in your experimental branch.
> 
> I'm not familiar with the BIND code, but this seems like a reasonable implementation to me, and suggests that the current spec is not too bad.
> 
> > You are assuming that it will take a lot of time for recursive servers to learn about these records.
> 
> Mostly I'm just counting roundtrips. SVCB queries are always issued in parallel to A/AAAA queries, so if SvcDomainName == owner-name, then there are already queries in flight for the necessary addresses (0 extra roundtrips). Anything that requires a followup query, whether by the recursive or by the client, adds some amount of latency.

Which has to be weighed up against how often it would actually save a query once support for these records is reasonably well deployed.   The only time when the name must differ is when a wildcard record is in use and the looked up name doesn't match target name.   The authoritative servers will be returning the target data as additional records.  Recursive server will accept such records as they will be in bailiwick.  Those records will then be returned to the client.

It will also provide no benefit for anything that is using a underscore prefix label.   Which reminds me that I need to add code to detect and prevent such wasted queries.   That's additional code that will need to be added to every client.  "." should only be mapped to the owner name for LDH owner names. 
> > Well if you really want it you would need to signal that the client supports intra RR compress for these types. That is easy enough to do with a EDNS option ...
> 
> If something like this already existed I think we would use it here, but inventing and standardizing it seems like a big project, not justified by the size of the problem.
> 
> I was thinking of something to avoid special-casing "." in this way, e.g. "The SvcDomainName is represented with a one-octet length prefix, followed by a buffer of that length. The buffer contains a domain name that fills the buffer. If the name is fully-qualified (ending in an empty label) then it is an absolute name; otherwise it is relative to the owner name.". However, I expect this would make your implementation more complex, not less, so I'm not suggesting this change.
