### ISSUE TITLE
Self-target

### ISSUE THREAD

**Issue by squarooticus** [MikeBishop/dns-alt-svc#252]
§ 2.5.2 says:

```
For ServiceMode SVCB RRs, if TargetName has the value ".", then the
owner name of this record MUST be used as the effective TargetName.
```

This makes sense for HTTPS and any future child RRTYPES that eschew Attrleafs, but it doesn't make a lot of sense for owner names with Attrleafs. Wouldn't it make sense for `.` to refer to the bare domain with the Attrleafs stripped?

**Comment by bemasc** [comment]
I think this is a plausible improvement.  I believe @marka63 previously suggested something similar.

However, I think it may already be too late for this change.  iOS 14 has shipped an implementation of draft-01, and this change would break compatibility with those devices.

**Comment by squarooticus** [comment]
What would be the downside? Fallback to authority? That seems like an acceptable outcome from shipping a draft implementation without a clean escape hatch.

**Comment by bemasc** [comment]
True, it's possible that this would be handled transparently via fallback.  ECH will remove the fallback, but (luckily?) ECH isn't defined yet.

**Comment by marka63** [comment]
This will only become a issue for clients that are not aware of this expected behaviour and the operator uses "." for the target name.

Apple has implicitly committed to shipping a fix for this if it is changed by releasing code against a draft.  Additionally iOS users are relatively quick to apply updates.  I would not be worried about making a change like this.

**Comment by enygren** [comment]
Per discussion, we're proposing to close this as a wontfix.  It is a nice feature but adds complexity and corner cases and is not necessary.  (There was a little WG support, but only a little.)
