### ISSUE TITLE
AliasMode clarification needed

### ISSUE THREAD

**Issue by brian-peter-dickson** [MikeBishop/dns-alt-svc#266]
The specification for AliasMode does not explicitly specify that it **MUST NOT have any SvcParams**.

This should be added to the first paragraph of the AliasMode section (currently 2.4.1).

Also, the current published draft incorrectly references AliasMode as section 2.4.3 (in the list in the body of 1.2, bullet 1 for SvcPriority.
Either that section (2.4.3) should explicitly indicate that priority=0 means AliasMode and point back to 2.4.1, or the section link for SvcPriority should be removed, or a separate link to the AliasMode section itself should be included in that bit of text (bullet 1 of 1.2).

**Comment by bemasc** [comment]
The current text is set up so that, while AliasMode currently doesn't have any params, it could have some in the future, and they would be ignored by all existing resolvers and clients.  I don't think an extension like that is likely to happen, but I also don't see a great need to explicitly rule it out.

I agree that the referencing regarding SvcPriority is a bit unclear.  I've proposed an adjustment to the section structure to reduce confusion in #267.

**Comment by brian-peter-dickson** [comment]
I think the text would be better if the AliasMode params were distinguished on the "publisher" vs "consumer" side.
I.e. that the current specification is, "MUST NOT" publish records with any SvcParams, but that the rules for handling AliasMode records SHOULD be prepared to handle AliasMode records with SvcParams (and that they should ignore them).
That would clarify what to publish (including what managed DNS providers need to support for their customers), while still accommodating future updates.
Clarity on the publishing side is NOT negotiable, honestly. The spec needs to be 100% complete and consistent on what is or is not in each type of record, as well as how those are to be handled.
(Thanks.)

**Comment by bemasc** [comment]
OK, I've opened a PR to clarify the requirements here (#269).
