### ISSUE TITLE
Please PLEASE simplify alpn and list representations and encoding/decoding

### ISSUE THREAD

**Issue by brian-peter-dickson** [MikeBishop/dns-alt-svc#268]
The stuff in Appendix A.1 is both moot and confusing.

If I understand correctly (after having to read and cross-reference many parts of this document, the ALPN RFC(s), and the IANA table for ALPN), the following is the case:
NO ALPN IDs HAVE EMBEDDED COMMAS.
Thus, there is NO need for quoted commas in any ALPN.
And, no other values (single or multi) have (or allow) embedded commas.

Can we please dispense with all of the fancy things showing how to quote commas and how to interpret quoted commas?
If necessary, place a caveat into the IANA table that ALPN values MUST NOT contain commas in their ID.

This reduces ALPN to wire format of one or more <length>string (where length is a single octet), and the presentation format is simply a comma-separated list of strings, possibly enclosed in quotes, with no other quoting necessary.

The SvcParameters object itself is, in presentation format, a list separated with whitespace, so there is no ambiguity between the list within an ALPN, and the list of SvcParameters. 

Please?

It would be nice to have a much simpler document, and much easier task for implementing things.

**Comment by bemasc** [comment]
You're correct: there are no defined ALPN IDs with embedded commas, and adopting that as an assumption would simplify the parsing considerably.  However, ALPN is defined as an "8-bit clean" field that can hold anything, so we would presumably have to "Update" RFC 7301 to introduce such a restriction.  I'm not convinced that we will find consensus in the TLS WG for that change.

I'm not really happy about where this has ended up, but I don't have an alternative that seems more likely to get consensus.

**Comment by MikeBishop** [comment]
This is similar in spirit to RFC 7838; while all ALPN tokens currently defined can be expressed as `tchar` for use in HTTP headers, that RFC still has to define how to percent-encode bytes which are not `tchar`s because they remain legal bytes for ALPN.  While modifying the ALPN registry would simplify that, I doubt that's something that should be driven through dnsop.

If you bring a draft to the TLS WG adding such restrictions to ALPN and it is adopted and progressed, we will happily update this draft to rely on that simplification, though.

**Comment by enygren** [comment]
Agreed with @MikeBishop and @bemasc .  I've never been a fan of this, but we're stuck with it unless we want to restrict to only support a subset of ALPNs.

**Comment by bemasc** [comment]
As I proceed with implementation, I'm increasingly leaning toward changing the delimeter from `\,` to `\\,`.  That would allow parsing with a universal first pass (converts `\\,` to `\,`), followed by a second pass that splits on all unescaped commas.  @marka63, would you be OK with that change?  The current text is written to match the code in your branch, but I'm finding that other implementations can't easily match that behavior (e.g. because they do unescaping before checking the RR type).

**Comment by marka63** [comment]
Then how do you encode a APLN name that contains ‘\,’?  '\\,’ and '\\\,’ both become ‘\,’ after the first pass.  The current solution is like it is because APLN names can be anything. 

> On 19 Nov 2020, at 05:59, Benjamin M. Schwartz <notifications@github.com> wrote:
> 
> 
> As I proceed with implementation, I'm increasingly leaning toward changing the delimeter from \, to \\,. That would allow parsing with a universal first pass (converts \\, to \,), followed by a second pass that splits on all unescaped commas. @marka63, would you be OK with that change? The current text is written to match the code in your branch, but I'm finding that other implementations can't easily match that behavior (e.g. because they do unescaping before checking the RR type).
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-- 
Mark Andrews, ISC
1 Seymour St., Dundas Valley, NSW 2117, Australia
PHONE: +61 2 9871 4742              INTERNET: marka@isc.org

**Comment by bemasc** [comment]
Yes, actual `\` in the ALPN would presumably need to be double-escaped (`\\\\` -> `\\` -> `\`).

**Comment by bemasc** [comment]
I've added a PR for this change in #282.  This doesn't eliminate the weirdness of ALPN, but it makes it considerably more contained.  I've now encountered multiple implementations where the draft-02 text would require totally restructuring the parser, so I think something like this change is necessary.

**Comment by bemasc** [comment]
I've merged #282.  This should substantially simplify the implementation of the ALPN zone file syntax, while still enabling representation of arbitrary ALPNs if necessary.  It should make life easier for everyone except @marka63, who has already implemented the previous behavior.  Sorry, Mark.

This is not set in stone, but we are approaching WGLC, so please speak now if you can't live with this version.

**Comment by marka63** [comment]
Part of the problem here is the assumption that all valid inputs to alpn can be parsed by the existing parser.  I would argue that they can't be.  The behaviour when parsing `alpn="a b,c"` is not defined by the existing specification.  character-string defines double-quote, content, double-quote.  It doesn't define keyname, equals, double-quote, content including space, double-quote.  I can't tell you if `alpn="a b,c"` would be come one or two tokens (`alpn=a` and `b,c"`) because the behaviour of double quote in that position is ill defined.  Is it a literal double quote or does it open up a double quoted string that continues the token?  We had to change our parser just to accept it.

BTW #282 has `\2\` which is illegal.  It is \DDD not '\D'.  `\050\`

**Comment by bemasc** [comment]
Yes, `SvcParam` is not a `<character-string>`, and cannot necessarily be parsed by an existing character-string parser.  However, I do think that the latest draft is easier to implement and more compatible.  I just updated two zone file implementations whose character-string parsers are able to handle the `key="a b,c"` syntax, but which would have been difficult to update for the previous value-list-char-string syntax.

Thanks for pointing out the `\2`.  Fix is in #286.
