### ISSUE TITLE
Can you use SVCB without A/AAAA?

### ISSUE THREAD

**Issue by martinthomson** [MikeBishop/dns-alt-svc#287]
It does not look like the draft considers the possibility that a protocol might depend on SVCB exclusively.

I think that it should be possible to deploy a protocol that only uses SVCB and not A/AAAA to find services.

The changes are fairly simple, you go from this text in Section 3:

>   2.  In parallel, issue AAAA/A queries for $ADDR_QNAME and a SVCB query for $SVCB_QNAME.  The answers for these may or may not include CNAME pointers before reaching one or more of these records.

To something like:

>   2.  If the service allows the use of address records, issue AAAA/A queries for $ADDR_QNAME and a SVCB query for $SVCB_QNAME in parallel.  Otherwise, issue a SVCB query for $SVCB_QNAME.  The answers for these may or may not include CNAME pointers before reaching one or more of these records.

... and

> Accordingly, clients SHALL connect to the endpoint consisting of $ADDR_QNAME, the authority endpoint's port number, and no SvcParams.

... becomes:

> Accordingly, if the service allows the use of address records, clients connect to the endpoint consisting of $ADDR_QNAME, the authority endpoint's port number, and no SvcParams.

Edit to note: The reason you might want to do this is that you have a service name (like "example.com"), but you don't want the A/AAAA records you use for another protocol (like HTTPS) being used for your fancy new protocol.

**Comment by bemasc** [comment]
I've proposed a paragraph on this in #288; please review.

I don't think the change proposed here is quite right.  Even if some new protocol relies on SVCB, I think it still makes sense for clients to issue address queries in parallel to the most likely TargetName, for latency hiding.  Issuing those queries doesn't mean they'll be used, even if they resolve, because the TargetName has precedence (if the prediction was wrong).

Ultimately, almost everything about SVCB can be modified by the protocol mapping specification for any protocol, so we don't need to enumerate every plausible behavior here, but I do think it's useful to mention the "SVCB-reliant" case.

**Comment by enygren** [comment]
To clarify, is the scenario that:

1) the A/AAAA on the same name as the record would never get used (unless the SvcDomainName was "." or otherwise pointed to the record)
or
2) The scenario that this is a protocol for which no address records are involved at all (eg, saying "use non-IP ansible protocol via a subspace network for a service located by some identifier specified as a SvcParam", or "connect via a non-IP unix-domain-socket via some namespace identified in a SvcParam")

**Comment by sftcd** [comment]
FWIW, to me, this really really looks like a discussion
that ought not be held only as a github issue.

S.

**Comment by bemasc** [comment]
Fixed by #291
