### ISSUE TITLE
Overuse of should/SHOULD

### ISSUE THREAD

**Issue by enygren** [MikeBishop/dns-alt-svc#355]
See this mailing list thread which recommends that we convert some SHOULD to MUST and which also points out some uses of "should" that would be better to fix:
https://mailarchive.ietf.org/arch/msg/dnsop/EhP4nvJV1WEa4wiEIPPZIdLvIhc/

**Comment by bemasc** [comment]
Francesca Palombini raised concerns about the following instances:

   Within a SVCB RRSet, all RRs SHOULD have the same Mode.  If an RRSet

   is used to impose an ordering on SVCB RRs.  SVCB RRs with a smaller
   SvcPriority value SHOULD be given preference over RRs with a larger
   SvcPriority value.

   In AliasMode, the SVCB record aliases a service to a TargetName.
   SVCB RRSets SHOULD only have a single resource record in AliasMode.
   If multiple are present, clients or recursive resolvers SHOULD pick
   one at random.

   In AliasMode, records SHOULD NOT include any SvcParams, and
   recipients MUST ignore any SvcParams that are present.

   Zone-file implementations
   SHOULD enforce self-consistency.

   If the client is SVCB-optional, and connecting using this list of
   endpoints has failed, the client SHOULD attempt non-SVCB connection
   modes.

   If the client enforces DNSSEC validation on A/AAAA responses, it
   SHOULD apply the same validation policy to SVCB.

   If the client is unable to complete SVCB resolution due to its chain
   length limit, the client SHOULD fall back to the authority endpoint,
   as if the origin's SVCB record did not exist.

   For compatibility with clients that require default transports, zone
   operators SHOULD ensure that at least one RR in each RRSet supports
   the default transports.

   Global Scoped Entry Registry [Attrleaf].  The scheme SHOULD have an
   entry in the IANA URI Schemes Registry [RFC7595].  The scheme SHOULD
   have a defined specification for use with SVCB.
