### ISSUE TITLE
Why is IPv6 in IPv4-mapped format allowed?

### ISSUE THREAD

**Issue by DesWurstes** [MikeBishop/dns-alt-svc#361]
`   example.com.   SVCB   1 example.com. ipv6hint="::ffff:198.51.100.100"` is allowed. I'd like to know the rationale behind this. Could you please give an example usecase?

**Comment by enygren** [comment]
This does seem like we should define it as an error case?  It seems like a worthwhile test vector, but it is not something we should encourage.  (Does someone know the rationale for it being in the test vectors?)

**Comment by DesWurstes** [comment]
If we don't have a strong reason to allow it or to forbid it we might as well leave it as Undefined Behavior so that every library does what consistency requires.

**Comment by DesWurstes** [comment]
@wtoorop I saw that you authored commit https://github.com/MikeBishop/dns-alt-svc/pull/312/commits/7e07bfb5e3512659e4bb0baed0d03eba94fb3e8d . Do you have anything to add? Was the commit on behalf of NLnetLabs?

**Comment by wtoorop** [comment]
A yes, sorry I used the wrong terminology, the presentation format in the test vector is not an IPv4-mapped IPv6, but the more generic IPv4 embedded IPv6 addresses, see: https://datatracker.ietf.org/doc/html/rfc6052#section-2.4 . So in order to correct this in the draft, the text `This example shows a single IPv6 hint in IPv4 mapped IPv6 presentation format.` should be changed to `This example shows a single IPv6 hint in IPv4 embedded IPv6 presentation format.`.
I can see that IPv4-mapped IPv6 would be an error semantically, but the presentation format (and the example used in the test-vector) is not. 

The context of commit 7e07bfb is that we (me, @pieterlexis, @TCY16  and the other Open Source DNS Software developers) were aligning the presentation format parsing implementations of our software in coordination with dnsop (see: https://mailarchive.ietf.org/arch/browse/dnsop/?gbt=1&index=okidoZWYPZc66vadCxwqXTkEA-c ). We did this by way of test vectors.

The rational for the test vector with the IPv4 embedded IPv6 text representation was that it is a valid alternative representation of an IPv6 address and because needs more than 40 octets to be represented. At the time some implementations had a too small buffer to accommodate this, which is why we included this test-vector.

**Comment by enygren** [comment]
So it looks like we should change the contents of the example back to:

`example.com.   SVCB   1 example.com. ipv6hint="2001:db8::198.51.100.100"`

and the title to:

`{: title="An IPv6 hint with an IPv4-embedded address"}`

I guess we could also have a MUST NOT about including IPv4-mapped addresses in IPv6 hints (and that client MUST ignore these).

**Comment by DesWurstes** [comment]
And maybe we should note that allowing ipv6-embedded-ipv6 is intended for DNS64 servers (only)?

**Comment by enygren** [comment]
> And maybe we should note that allowing ipv6-embedded-ipv6 is intended for DNS64 servers (only)?

I don't think we need to mention this.  On the wire it is all just binary so ipv4-embedded-ipv6 is just a convenience for zone file authors, and there are some operational reasons to use it.  (ie, some server networks will use a common /64 for a cluster and then embed the IPv4 addresses of the servers in the cluster into the /64 so this might make scripting and readability of a zone file better.)
