### ISSUE TITLE
Trust DNSSEC-verified HTTPS records

### ISSUE THREAD

**Issue by Saklad5** [MikeBishop/dns-alt-svc#401]
https://github.com/MikeBishop/dns-alt-svc/blob/1dac79072773c0ad071429655d50eac48f41096b/draft-ietf-dnsop-svcb-https.md#L1129-L1138

I understand making DNSSEC optional, and I understand that HTTPS records cannot be trusted in its absence. However, I see no reason to prohibit parameters that are safe _only_ in the presence of DNSSEC.

I feel it would make much more sense to mandate that such parameters MUST be ignored unless DNSSEC succeeds. This could be easily accomplished by flagging the corresponding entries as "secure" in the IANA registries.

---

For instance, there _could_ be an SvcParamKey corresponding to the Alt-Svc "persist" parameter, but it would only be acknowledged over a trusted channel (that is, DNSSEC).

I'm not calling for such an entry in this issue, to be clear: I simply want the option of having such entries in the future.

**Comment by bemasc** [comment]
I think your logic is reasonable, and if support for this kind of behavior becomes necessary in the future, we can always publish a new draft that discusses this case.  However, given the very low level of end-to-end DNSSEC deployment, I think it's good that we didn't add complexity to cover that in this document.

In the specific case of "persist", there are a few additional problems:
1. This parameter is from Alt-Svc, which is an HTTP concept.  End-to-end DNSSEC validation for HTTP is extremely rare, and mixing DNSSEC and PKI authentication of HTTP origins could create confusion.
2. It's not clear that "persist" would be safe to use even with DNSSEC, because DNS caches are not generally partitioned by page origin.  Cross-origin caching of "persist" could create an unwanted tracking vector in HTTP clients that have restricted support for third-party cookies.

**Comment by Saklad5** [comment]
DNSSEC has become much more practical in recent years due to ECC, and adoption is increasing. I'd rather leave the option open and simply not submit any "secure" entries to the registry for the moment. I'm concerned this would be much harder to tack on later.

If you're sure you want to leave it for now, though, that's your prerogative.

**Comment by bemasc** [comment]
This is effectively equivalent to the current situation.  Clients will ignore parameters they don't understand, so a new parameter could declare that it is to be ignored in unsigned records.

If you come up with an idea for a SvcParam that depends on DNSSEC, please feel free to propose it.  I don't see any real impediment to that.

For Opportunistic Onions, I would start by checking with the Tor team about whether they are willing and able to run end-to-end DNSSEC in Tor Browser.  I suspect that there are some technical challenges and performance concerns that will have to be solved first.

**Comment by Saklad5** [comment]
> This is effectively equivalent to the current situation. Clients will ignore parameters they don't understand, so a new parameter could declare that it is to be ignored in unsigned records.

That's an excellent point. I forget that IANA registries don't actually need to be machine-readable, so there wouldn't be an issue with just adding the "secure" flag in a future standard.

**Comment by Saklad5** [comment]
Actually, in that case, why is there even a MUST NOT condition at all? What is it constraining?
