### ISSUE TITLE
Reduce emphasis on HTTPSSVC <-> Alt-Svc equivalence

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#60]
Given that conversion between HTTPSSVC and Alt-Svc is now potentially quite lossy (any unmapped or unrecognized keys are dropped) and has unclear security properties, we should probably de-emphasize the idea of converting between them, and focus on their parallel structure instead.

**Comment by davidben** [comment]
On the unclear security properties front, I'm a little dubious of this text:

> SVCB/HTTPSSVC RRs and Alt-Svc Field Values are intended for distribution over untrusted channels, and clients are REQUIRED to verify that the alternative service is authoritative for the origin (Section 2.1 of {{!AltSvc}}).

The second clause does follow from section 2.1, but I'm not sure the first clause does. Alt-Svc is currently only ever delivered over a connection that is authoritative for the origin. HTTPSSVC is not. For more fun, neither is even strictly more secure than the other, depending on to what extent URLs like https://university.example/~some-student/evil.php are in your threat model.

This is somewhat a theoretical issue since HTTPSSVC is appropriate for all the Alt-Svc keys that are currently defined. Perhaps we need to freeze Alt-Svc or be very discerning about how to define it going forwards. There's already been some confusion in the security models in https://github.com/httpwg/http-extensions/pull/866.

(Really this reflects flaws in Alt-Svc than anything else. It tries to solve too many problems at once and awkwardness like this and #58 are the result.)

**Comment by MikeBishop** [comment]
Alt-Svc is supposed to be delivered over a connection that is a) authorized to speak for the origin (either the origin itself or a duly appointed alternative), and b) at least as secure as the origin.  For an https:// origin, that means it came over TLS; for an http:// origin, it's fine if it didn't.

However, if you can control the origin's DNS records and possess a certificate for the origin, you're as authorized to speak for the origin as it gets, in practice.  I think to achieve the second requirement, you probably do want guarantees that it wasn't modified in transit -- at least DoT/DoH (because the DNS server and anything upstream of it could have subverted DNS anyway), but even better if you have DNSsec.

**Comment by davidben** [comment]
DoT/DoH does not give you the second requirement because the resolver does not have a certificate. That's exactly the unclear security property.

**Comment by MikeBishop** [comment]
I'm confused.  RFC 8484 says that the resolver's identity is validated per RFC2818, i.e. with a cert.  A cursory read of DoT suggests that the client at a minimum *need not* check the server's validity.

Regardless, this seems to all circle back to the question of whether DNS is a security factor in HTTP.  If a DNS entry has come from an unauthenticated source, but the certificate is valid -- is that sufficient?  What if the DNS entry was DNSsec-signed?

There has been fairly strong consensus that holding the relevant certificate is enough proof of authority, DNS notwithstanding.  I happen to think that consensus is somewhat misguided, but it's at least consistent.

**Comment by bemasc** [comment]
My conclusion from this discussion is that, while nothing in Alt-Svc currently requires secure delivery, the requirements on Alt-Svc delivery security are not actually specified anywhere, so Alt-Svc could theoretically be extended in a way that relies on secure delivery.  I'll update the text to avoid implying otherwise.

**Comment by davidben** [comment]
Right, what @bemasc says. @MikeBishop, I think you and I are talking about different things. My comments have nothing to do with the DNS second factor. It's the much more important origin certificate first factor that's missing. While I certainly hope any DoT or DoH client will check the resolver's certificate (otherwise what is the point?), that just strengthens the second factor. It doesn't replace the first factor.

**Comment by davidben** [comment]
And, to clarify, this isn't a comment on HTTPSSVC in a vacuum. DNS-delivered HTTPSSVC is just fine without that first factor because all fields currently defined there give no more power than the resolver already has. (It can make the site unavailable, or cause information it already has (SNI) to be leaked.)

The concern is simply that HTTPSSVC asserts a strong association with Alt-Svc (happily less so now), which is typically delivered in a context that has *both* factors. (With the footnote that, if your threat model includes `users/attacker/evil.php` delivering a bad origin-wide header, Alt-Svc isn't quite strictly stronger.) I'd like to avoid a situation where someone adds an Alt-Svc field which only makes sense in the latter but not the former, such as https://github.com/httpwg/http-extensions/pull/866.

**Comment by MikeBishop** [comment]
@davidben, I think I see what you're suggesting.  Does this capture it?

When Alt-Svc is delivered over HTTPS, you have trust -- from the certificate and possibly from the earlier DNS resolution -- that the record was in fact delivered by the origin.  That is, you trust the record itself, and the certificate check on connection is only to verify that the alternative connection hasn't been subverted.

With HTTPSSVC, unless you have DNSsec, there are one or more intermediaries who might have changed that record en route, meaning you can't fully trust it.  The certificate check on the declared alternative therefore serves to confirm the authenticity of the record itself, not just the connection to the alternative.

This is also true for Alt-Svc delivered over HTTP -- it could have been tampered with in transit, and therefore only the certificate confirms that the Alt-Svc field was legitimate.  An intermediary who could tamper with the Alt-Svc field could also have tampered with the content, but Alt-Svc permits them to persistent that control.

**Comment by davidben** [comment]
I think we're broadly in agreement. Some nitpicks:

> That is, you trust the [Alt-Svc] record itself, and the certificate check on connection is only to verify that the alternative connection hasn't been subverted.
>
> [...] The certificate check on the [HTTPSSVC-]declared alternative therefore serves to confirm the authenticity of the record itself, not just the connection to the alternative.

I think your framing uses assumptions from the currently defined Alt-Svc and HTTPSSVC parameters. Both systems are extensible and I don't see any text in Alt-Svc which implies new parameters must account for the possibility of untrusted records, which means treating them equivalent is problematic.

Note also the certificate check on the HTTPSSVC alternative does *not* confirm authenticity of the record. Maybe one of the parameters not directly involved in verification was bad. Or maybe it was all invalid, but the network directed the invalid alternative name to the real server, in an attempt to get you to believe the rest of the HTTPSSVC record. (This is in the same way certificate checks do not validate the A/AAAA record you used. You can't skip TLS tomorrow assuming the IP was good.)

> [...] unless you have DNSsec [...]

The Web PKI and DNSSEC are different PKIs with different properties, so they're not automatically interchangeable. For better or worse, most HTTPS uses these days are based off the Web PKI, not the DNSSEC PKI. But, yeah, DNSSEC is certainly trying to actually authenticate the record, unlike DoT/DoH.

> This is also true for Alt-Svc delivered over HTTP -- it could have been tampered with in transit, and therefore only the certificate confirms that the Alt-Svc field was legitimate.

I not quite sure what this is referring to. You shouldn't be able to deliver an Alt-Svc for https://example.com over http://example.com and the latter has no certificate. (And, per above, the certificate check wouldn't retroactively verify the Alt-Svc record.)

Is this a reference to our RFC8164 discussion in issue #58? That was about a different (but related) issue: believing Alt-Svc shadows HTTPSSVC means Alt-Svc will shadow any HTTPSSVC-only features, current or future. We already have one HTTPSSVC-only feature: for HTTP origins, HTTPSSVC automatically redirects. Alt-Svc is mostly HTTPS, but RFC8164 defines one for HTTP origins.
