### ISSUE TITLE
Does HSTS apply if you fall back to A?

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#91]
We should clarify whether the HSTS implication applies to the fallback IPs, and also clarify that it _does_ apply to AliasForm.

**Comment by bemasc** [comment]
Conclusion: yes, and we need to be explicit about it.

**Comment by davidben** [comment]
+1

**Comment by enygren** [comment]
Example corner-case to think through as part of this: if something causes you to give up (eg, chain too long) should the HSTS-style behavior still apply?  And in the failure-case regime how long should this behavior change be cached?

**Comment by davidben** [comment]
I don't think HTTP and HTTPS URLs would make the same sort of HTTPSSVC queries anyway. If the HSTS behavior is triggered from DNS, the HTTP stack would need to effectively fail the HTTP request and bubble the error up past the HTTP cache to the redirect-handling and URL-dispatching layer (otherwise the URL can't change) to retry the request. Any DNS queries would most likely then be *reissued* for the HTTPS URL, though almost certainly cached.

That means that following AliasForms and whatnot doesn't really apply the HSTS flow. As soon as you see an HTTPSSVC record, you can bail. (Real HSTS does not have this oddity because we resolve HSTS before we decide to hit the network or anything.)
