### ISSUE TITLE
Explicitly state semantics of SvcParamKey ranges

### ISSUE THREAD

**Issue by dmcardle** [MikeBishop/dns-alt-svc#98]
Can we nail down the semantics of the different SvcParamKey ranges?

To start with:

* Reserved => FAIL_PARSE
* PrivateUse => EXTRACT_OR_SKIP
* ALPN | PORT | ESNICONFIG | ... => EXTRACT_OR_SKIP

I can't see any reason why we should accept records that contain reserved keys.

**Comment by dmcardle** [comment]
@davidben

**Comment by davidben** [comment]
Usually private use stuff isn't treated different from other unknown keys since it's just a way for folks to allocate things without going through the registries. Not sure what the reserved ones are for. I guess `key0` is so people can conveniently use zero for a nullable `SvcParamKey`. Was `key5` just used in an earlier iteration of the draft? In that case, we probably want to treat it as unknown since it's just a marker to not allocate it.

**Comment by dmcardle** [comment]
As best as I can tell, key5 is there so that ipv4=4 and ipv6=6!

Can you expand on nullable SvcParamKey? Seems you could just omit the SvcParam entirely in that situation.

**Comment by davidben** [comment]
I just mean that if you're writing some function that wants to return a `std::optional<SvcParamKey>` or `Option<SvcParamKey>` or `SvcParamKey?` or whatever but your language doesn't have a convenient way to express option types, you can just return a `uint16_t` and have zero be the null value. :-)

**Comment by bemasc** [comment]
"Reserved" doesn't really mean "disallowed", exactly.  It's more like "not yet allocated".  Parsers can't generally reject reserved values, because they could have been allocated after the code was written.

I like the idea of clarifying that zero is "permanently reserved" for the use @davidben described.  Maybe we can call it "null" or something...

**Comment by dmcardle** [comment]
OK, I'm not entirely sure I get the distinction.

I figured the unmentioned key values (7..65279) were the "not yet allocated" keys, and that the "reserved" keys (0, 5, 65535) were permanently reserved.

Are you saying that "reserved" lies somewhere between "permanently reserved" (never to be used) and "not yet allocated"?

I think it's worth explicitly describing what to do with each *type* of key.  My instinct was to reject records that contain reserved keys, since they must be nonsense :stuck_out_tongue:.

**Comment by bemasc** [comment]
OK, we should improve the table to avoid this ambiguity.

**Comment by davidben** [comment]
FWIW I don't have a preference either way about whether we reserve zero like that. That was me attempting to divine what it was reserved for. If it's a new idea to you, apparently I was wrong! :-)

**Comment by davidben** [comment]
I would advocate not having random permanently reserved values that parsers are meant to reject though. That's more fuss for no benefit. If we want zero to be null, that's a reason, but key5 has no reason to be special.

Perhaps just delete the key5 row? Then it's the same as the remaining unassigned range.

**Comment by dmcardle** [comment]
Agreed, fewer rules is better. I'd support squashing key5.

What's the rationale for key65535 being reserved?

**Comment by MikeBishop** [comment]
Closing in favor of #154.

**Comment by enygren** [comment]
See also #154 which may be worth addressing at the same time.
