### ISSUE TITLE
Clarify Alias wire format and motivation for binary SvcFieldValue encoding

### ISSUE THREAD

**Issue by bemasc** [MikeBishop/dns-alt-svc#99]
@miekg has asked for two related clarifications:
1. How is it that the AliasForm and ServiceForm encodings are compatible?
2. Why not reuse the TXT/SPF format?

**Comment by miekg** [comment]
If this is previously discussed I am happy to read those emails.

Re 1.: the text in the 01 draft is unclear to me that these two encoding (as proposed) are in fact identical.

Re 2.: Easiest for us is to just re-use the TXT encoding, the draft talks about limit length (255 octets) per txt segment, which is true, but the total size can still be more than that. Downside is that parsing of the key, values must be done by the client, instead of the DNS client. But things like \DDD are supported within TXT as well.

See https://github.com/miekg/dns/issues/1064 for our bug to add this.

**Comment by enygren** [comment]
This has been extensively discussed in the WG.  Can we close this?
